import { supabase } from '@/lib/supabase';
import type { Alert, AlertSeverity } from '@/types';

export interface CreateAlertPayload {
  patientId?  : string;          // uuid — omit for system-wide alerts
  patientName : string;
  type        : string;
  severity    : AlertSeverity;
  message     : string;
  value       : string;
  threshold?  : string;
}

/**
 * Insert a manual alert directly into the `alerts` table.
 * The useAlerts realtime subscription will pick it up automatically.
 */
export async function createAlert(payload: CreateAlertPayload): Promise<Alert> {
  const row = {
    "patientId"   : payload.patientId   ?? null,
    "patientName" : payload.patientName,
    type          : payload.type,
    severity      : payload.severity,
    message       : payload.message,
    value         : payload.value,
    threshold     : payload.threshold ?? '—',
    // `id` and `timestamp` are generated by the DB
  };

  const { data, error } = await supabase
    .from('alerts')
    .insert(row)
    .select()
    .single();

  if (error) {
    console.error('[createAlert] Supabase insert error:', error);
    throw error;
  }

  return data as Alert;
}